export interface SurahMeta {
    id: number;
    name: string;
    arabic: string;
    translation: string;
}

export const ALL_SURAHS: SurahMeta[] = [
  { id: 1, name: "Al-Fatiha", arabic: "الفاتحة", translation: "The Opening" },
  { id: 2, name: "Al-Baqarah", arabic: "البقرة", translation: "The Cow" },
  { id: 3, name: "Aal-E-Imran", arabic: "آل عمران", translation: "The Family of Imran" },
  { id: 4, name: "An-Nisa", arabic: "النساء", translation: "The Women" },
  { id: 5, name: "Al-Ma'idah", arabic: "المائدة", translation: "The Table Spread" },
  { id: 6, name: "Al-An'am", arabic: "الأنعام", translation: "The Cattle" },
  { id: 7, name: "Al-A'raf", arabic: "الأعراف", translation: "The Heights" },
  { id: 8, name: "Al-Anfal", arabic: "الأنفال", translation: "The Spoils of War" },
  { id: 9, name: "At-Tawbah", arabic: "التوبة", translation: "The Repentance" },
  { id: 10, name: "Yunus", arabic: "يونس", translation: "Jonah" },
  { id: 11, name: "Hud", arabic: "هود", translation: "Hud" },
  { id: 12, name: "Yusuf", arabic: "يوسف", translation: "Joseph" },
  { id: 13, name: "Ar-Ra'd", arabic: "الرعد", translation: "The Thunder" },
  { id: 14, name: "Ibrahim", arabic: "ابراهيم", translation: "Abraham" },
  { id: 15, name: "Al-Hijr", arabic: "الحجر", translation: "The Rocky Tract" },
  { id: 16, name: "An-Nahl", arabic: "النحل", translation: "The Bee" },
  { id: 17, name: "Al-Isra", arabic: "الإسراء", translation: "The Night Journey" },
  { id: 18, name: "Al-Kahf", arabic: "الكهف", translation: "The Cave" },
  { id: 19, name: "Maryam", arabic: "مريم", translation: "Mary" },
  { id: 20, name: "Taha", arabic: "طه", translation: "Taha" },
  { id: 21, name: "Al-Anbiya", arabic: "الأنبياء", translation: "The Prophets" },
  { id: 22, name: "Al-Hajj", arabic: "الحج", translation: "The Pilgrimage" },
  { id: 23, name: "Al-Mu'minun", arabic: "المؤمنون", translation: "The Believers" },
  { id: 24, name: "An-Nur", arabic: "النور", translation: "The Light" },
  { id: 25, name: "Al-Furqan", arabic: "الفرقان", translation: "The Criterion" },
  { id: 26, name: "Ash-Shu'ara", arabic: "الشعراء", translation: "The Poets" },
  { id: 27, name: "An-Naml", arabic: "النمل", translation: "The Ant" },
  { id: 28, name: "Al-Qasas", arabic: "القصص", translation: "The Stories" },
  { id: 29, name: "Al-Ankabut", arabic: "العنكبوت", translation: "The Spider" },
  { id: 30, name: "Ar-Rum", arabic: "الروم", translation: "The Romans" },
  { id: 31, name: "Luqman", arabic: "لقمان", translation: "Luqman" },
  { id: 32, name: "As-Sajdah", arabic: "السجدة", translation: "The Prostration" },
  { id: 33, name: "Al-Ahzab", arabic: "الأحزاب", translation: "The Combined Forces" },
  { id: 34, name: "Saba", arabic: "سبإ", translation: "Sheba" },
  { id: 35, name: "Fatir", arabic: "فاطر", translation: "Originator" },
  { id: 36, name: "Ya-Sin", arabic: "يس", translation: "Ya Sin" },
  { id: 37, name: "As-Saffat", arabic: "الصافات", translation: "Those who set the Ranks" },
  { id: 38, name: "Sad", arabic: "ص", translation: "The Letter 'Saad'" },
  { id: 39, name: "Az-Zumar", arabic: "الزمر", translation: "The Troops" },
  { id: 40, name: "Ghafir", arabic: "غافر", translation: "The Forgiver" },
  { id: 41, name: "Fussilat", arabic: "فصلت", translation: "Explained in Detail" },
  { id: 42, name: "Ash-Shuraa", arabic: "الشورى", translation: "The Consultation" },
  { id: 43, name: "Az-Zukhruf", arabic: "الزخرف", translation: "The Ornaments of Gold" },
  { id: 44, name: "Ad-Dukhan", arabic: "الدخان", translation: "The Smoke" },
  { id: 45, name: "Al-Jathiyah", arabic: "الجاثية", translation: "The Crouching" },
  { id: 46, name: "Al-Ahqaf", arabic: "الأحقاف", translation: "The Wind-Curved Sandhills" },
  { id: 47, name: "Muhammad", arabic: "محمد", translation: "Muhammad" },
  { id: 48, name: "Al-Fath", arabic: "الفتح", translation: "The Victory" },
  { id: 49, name: "Al-Hujurat", arabic: "الحجرات", translation: "The Rooms" },
  { id: 50, name: "Qaf", arabic: "ق", translation: "The Letter 'Qaf'" },
  { id: 51, name: "Adh-Dhariyat", arabic: "الذاريات", translation: "The Winnowing Winds" },
  { id: 52, name: "At-Tur", arabic: "الطور", translation: "The Mount" },
  { id: 53, name: "An-Najm", arabic: "النجم", translation: "The Star" },
  { id: 54, name: "Al-Qamar", arabic: "القمر", translation: "The Moon" },
  { id: 55, name: "Ar-Rahman", arabic: "الرحمن", translation: "The Most Merciful" },
  { id: 56, name: "Al-Waqi'ah", arabic: "الواقعة", translation: "The Inevitable" },
  { id: 57, name: "Al-Hadid", arabic: "الحديد", translation: "The Iron" },
  { id: 58, name: "Al-Mujadila", arabic: "المجادلة", translation: "The Pleading Woman" },
  { id: 59, name: "Al-Hashr", arabic: "الحشر", translation: "The Exile" },
  { id: 60, name: "Al-Mumtahanah", arabic: "الممتحنة", translation: "She that is to be examined" },
  { id: 61, name: "As-Saf", arabic: "الصف", translation: "The Ranks" },
  { id: 62, name: "Al-Jumu'ah", arabic: "الجمعة", translation: "The Congregation, Friday" },
  { id: 63, name: "Al-Munafiqun", arabic: "المنافقون", translation: "The Hypocrites" },
  { id: 64, name: "At-Taghabun", arabic: "التغابن", translation: "The Mutual Disillusion" },
  { id: 65, name: "At-Talaq", arabic: "الطلاق", translation: "The Divorce" },
  { id: 66, name: "At-Tahrim", arabic: "التحريم", translation: "The Prohibition" },
  { id: 67, name: "Al-Mulk", arabic: "الملك", translation: "The Sovereignty" },
  { id: 68, name: "Al-Qalam", arabic: "القلم", translation: "The Pen" },
  { id: 69, name: "Al-Haqqah", arabic: "الحاقة", translation: "The Reality" },
  { id: 70, name: "Al-Ma'arij", arabic: "المعارج", translation: "The Ascending Stairways" },
  { id: 71, name: "Nuh", arabic: "نوح", translation: "Noah" },
  { id: 72, name: "Al-Jinn", arabic: "الجن", translation: "The Jinn" },
  { id: 73, name: "Al-Muzzammil", arabic: "المزمل", translation: "The Enshrouded One" },
  { id: 74, name: "Al-Muddaththir", arabic: "المدثر", translation: "The Cloaked One" },
  { id: 75, name: "Al-Qiyamah", arabic: "القيامة", translation: "The Resurrection" },
  { id: 76, name: "Al-Insan", arabic: "الانسان", translation: "Man" },
  { id: 77, name: "Al-Mursalat", arabic: "المرسلات", translation: "The Emissaries" },
  { id: 78, name: "An-Naba", arabic: "النبإ", translation: "The Tidings" },
  { id: 79, name: "An-Nazi'at", arabic: "النازعات", translation: "Those who drag forth" },
  { id: 80, name: "Abasa", arabic: "عبس", translation: "He Frowned" },
  { id: 81, name: "At-Takwir", arabic: "التكوير", translation: "The Overthrowing" },
  { id: 82, name: "Al-Infitar", arabic: "الإنفطار", translation: "The Cleaving" },
  { id: 83, name: "Al-Mutaffifin", arabic: "المطففين", translation: "The Defrauding" },
  { id: 84, name: "Al-Inshiqaq", arabic: "الإنشقاق", translation: "The Splitting Open" },
  { id: 85, name: "Al-Buruj", arabic: "البروج", translation: "The Mansions of the Stars" },
  { id: 86, name: "At-Tariq", arabic: "الطارق", translation: "The Nightcommer" },
  { id: 87, name: "Al-A'la", arabic: "الأعلى", translation: "The Most High" },
  { id: 88, name: "Al-Ghashiyah", arabic: "الغاشية", translation: "The Overwhelming" },
  { id: 89, name: "Al-Fajr", arabic: "الفجر", translation: "The Dawn" },
  { id: 90, name: "Al-Balad", arabic: "البلد", translation: "The City" },
  { id: 91, name: "Ash-Shams", arabic: "الشمس", translation: "The Sun" },
  { id: 92, name: "Al-Layl", arabic: "الليل", translation: "The Night" },
  { id: 93, name: "Ad-Duhaa", arabic: "الضحى", translation: "The Morning Hours" },
  { id: 94, name: "Ash-Sharh", arabic: "الشرح", translation: "The Relief" },
  { id: 95, name: "At-Tin", arabic: "التين", translation: "The Fig" },
  { id: 96, name: "Al-Alaq", arabic: "العلق", translation: "The Clot" },
  { id: 97, name: "Al-Qadr", arabic: "القدر", translation: "The Power" },
  { id: 98, name: "Al-Bayyinah", arabic: "البينة", translation: "The Clear Proof" },
  { id: 99, name: "Az-Zalzalah", arabic: "الزلزلة", translation: "The Earthquake" },
  { id: 100, name: "Al-Adiyat", arabic: "العاديات", translation: "The Courser" },
  { id: 101, name: "Al-Qari'ah", arabic: "القارعة", translation: "The Calamity" },
  { id: 102, name: "At-Takathur", arabic: "التكاثر", translation: "The Piling Up" },
  { id: 103, name: "Al-Asr", arabic: "العصر", translation: "The Time" },
  { id: 104, name: "Al-Humazah", arabic: "الهمزة", translation: "The Slanderer" },
  { id: 105, name: "Al-Fil", arabic: "الفيل", translation: "The Elephant" },
  { id: 106, name: "Quraysh", arabic: "قريش", translation: "Quraysh" },
  { id: 107, name: "Al-Ma'un", arabic: "الماعون", translation: "The Small Kindnesses" },
  { id: 108, name: "Al-Kawthar", arabic: "الكوثر", translation: "The Abundance" },
  { id: 109, name: "Al-Kafirun", arabic: "الكافرون", translation: "The Disbelievers" },
  { id: 110, name: "An-Nasr", arabic: "النصر", translation: "The Divine Support" },
  { id: 111, name: "Al-Masad", arabic: "المسد", translation: "The Palm Fiber" },
  { id: 112, name: "Al-Ikhlas", arabic: "الإخلاص", translation: "The Sincerity" },
  { id: 113, name: "Al-Falaq", arabic: "الفلق", translation: "The Daybreak" },
  { id: 114, name: "An-Nas", arabic: "الناس", translation: "Mankind" },
];
