export const PRAYER_NAMES = ['Fajr', 'Sunrise', 'Dhuhr', 'Asr', 'Maghrib', 'Isha'];

export const ALLAH_NAMES = [
  { "id": 1, "name": "Ar-Rahman", "transliteration": "الرحمن", "en": "The Beneficent" },
  { "id": 2, "name": "Ar-Rahim", "transliteration": "الرحيم", "en": "The Merciful" },
  { "id": 3, "name": "Al-Malik", "transliteration": "الملك", "en": "The King" },
  { "id": 4, "name": "Al-Quddus", "transliteration": "القدوس", "en": "The Most Holy" },
  { "id": 5, "name": "As-Salam", "transliteration": "السلام", "en": "The Source of Peace" },
  { "id": 6, "name": "Al-Mu'min", "transliteration": "المؤمن", "en": "The Guardian of Faith" },
  { "id": 7, "name": "Al-Muhaymin", "transliteration": "المهيمن", "en": "The Protector" },
  { "id": 8, "name": "Al-Aziz", "transliteration": "العزيز", "en": "The Mighty" },
  { "id": 9, "name": "Al-Jabbar", "transliteration": "الجبار", "en": "The Compeller" },
  { "id": 10, "name": "Al-Mutakabbir", "transliteration": "المتكبر", "en": "The Majestic" },
  { "id": 11, "name": "Al-Khaliq", "transliteration": "الخالق", "en": "The Creator" },
  { "id": 12, "name": "Al-Bari'", "transliteration": "البارئ", "en": "The Maker" },
  { "id": 13, "name": "Al-Musawwir", "transliteration": "المصور", "en": "The Fashioner of Forms" },
  { "id": 14, "name": "Al-Ghaffar", "transliteration": "الغفار", "en": "The Forgiver" },
  { "id": 15, "name": "Al-Qahhar", "transliteration": "القهار", "en": "The Subduer" },
  { "id": 16, "name": "Al-Wahhab", "transliteration": "الوهاب", "en": "The Giver of All" },
  { "id": 17, "name": "Ar-Razzaq", "transliteration": "الرزاق", "en": "The Sustainer" },
  { "id": 18, "name": "Al-Fattah", "transliteration": "الفتاح", "en": "The Opener" },
  { "id": 19, "name": "Al-Alim", "transliteration": "العليم", "en": "The Knower of All" },
  { "id": 20, "name": "Al-Qabid", "transliteration": "القابض", "en": "The Constrictor" },
  { "id": 21, "name": "Al-Basit", "transliteration": "الباسط", "en": "The Reliever" },
  { "id": 22, "name": "Al-Khafid", "transliteration": "الخافض", "en": "The Abaser" },
  { "id": 23, "name": "Ar-Rafi'", "transliteration": "الرافع", "en": "The Exalter" },
  { "id": 24, "name": "Al-Mu'izz", "transliteration": "المعز", "en": "The Bestower of Honors" },
  { "id": 25, "name": "Al-Mudhill", "transliteration": "المذل", "en": "The Humiliator" },
  { "id": 26, "name": "As-Sami'", "transliteration": "السميع", "en": "The Hearer of All" },
  { "id": 27, "name": "Al-Basir", "transliteration": "البصير", "en": "The Seer of All" },
  { "id": 28, "name": "Al-Hakam", "transliteration": "الحكم", "en": "The Judge" },
  { "id": 29, "name": "Al-Adl", "transliteration": "العدل", "en": "The Just" },
  { "id": 30, "name": "Al-Latif", "transliteration": "اللطيف", "en": "The Subtle One" },
  { "id": 31, "name": "Al-Khabir", "transliteration": "الخبير", "en": "The All-Aware" },
  { "id": 32, "name": "Al-Halim", "transliteration": "الحليم", "en": "The Forbearing" },
  { "id": 33, "name": "Al-Azim", "transliteration": "العظيم", "en": "The Magnificent" },
  { "id": 34, "name": "Al-Ghafur", "transliteration": "الغفور", "en": "The Forgiver and Hider of Faults" },
  { "id": 35, "name": "Ash-Shakur", "transliteration": "الشكور", "en": "The Rewarder of Thankfulness" },
  { "id": 36, "name": "Al-Ali", "transliteration": "العلي", "en": "The Highest" },
  { "id": 37, "name": "Al-Kabir", "transliteration": "الكبير", "en": "The Greatest" },
  { "id": 38, "name": "Al-Hafiz", "transliteration": "الحفيظ", "en": "The Preserver" },
  { "id": 39, "name": "Al-Muqit", "transliteration": "المقيت", "en": "The Nourisher" },
  { "id": 40, "name": "Al-Hasib", "transliteration": "الحسيب", "en": "The Accounter" },
  { "id": 41, "name": "Al-Jalil", "transliteration": "الجليل", "en": "The Mighty" },
  { "id": 42, "name": "Al-Karim", "transliteration": "الكريم", "en": "The Generous" },
  { "id": 43, "name": "Ar-Raqib", "transliteration": "الرقيب", "en": "The Watchful One" },
  { "id": 44, "name": "Al-Mujib", "transliteration": "المجيب", "en": "The Responder to Prayer" },
  { "id": 45, "name": "Al-Wasi'", "transliteration": "الواسع", "en": "The All-Comprehending" },
  { "id": 46, "name": "Al-Hakim", "transliteration": "الحكيم", "en": "The Perfectly Wise" },
  { "id": 47, "name": "Al-Wadud", "transliteration": "الودود", "en": "The Loving One" },
  { "id": 48, "name": "Al-Majid", "transliteration": "المجيد", "en": "The Majestic One" },
  { "id": 49, "name": "Al-Ba'ith", "transliteration": "الباعث", "en": "The Resurrector" },
  { "id": 50, "name": "Ash-Shahid", "transliteration": "الشهيد", "en": "The Witness" },
  { "id": 51, "name": "Al-Haqq", "transliteration": "الحق", "en": "The Truth" },
  { "id": 52, "name": "Al-Wakil", "transliteration": "الوكيل", "en": "The Trustee" },
  { "id": 53, "name": "Al-Qawi", "transliteration": "القوي", "en": "The Possessor of All Strength" },
  { "id": 54, "name": "Al-Matin", "transliteration": "المتين", "en": "The Forceful One" },
  { "id": 55, "name": "Al-Wali", "transliteration": "الولي", "en": "The Governor" },
  { "id": 56, "name": "Al-Hamid", "transliteration": "الحميد", "en": "The Praised One" },
  { "id": 57, "name": "Al-Muhsi", "transliteration": "المحصي", "en": "The Appraiser" },
  { "id": 58, "name": "Al-Mubdi'", "transliteration": "المبدئ", "en": "The Originator" },
  { "id": 59, "name": "Al-Mu'id", "transliteration": "المعيد", "en": "The Restorer" },
  { "id": 60, "name": "Al-Muhyi", "transliteration": "المحيي", "en": "The Giver of Life" },
  { "id": 61, "name": "Al-Mumit", "transliteration": "المميت", "en": "The Taker of Life" },
  { "id": 62, "name": "Al-Hayy", "transliteration": "الحي", "en": "The Ever Living One" },
  { "id": 63, "name": "Al-Qayyum", "transliteration": "القيوم", "en": "The Self-Existing One" },
  { "id": 64, "name": "Al-Wajid", "transliteration": "الواجد", "en": "The Finder" },
  { "id": 65, "name": "Al-Majid", "transliteration": "الماجد", "en": "The Glorious" },
  { "id": 66, "name": "Al-Wahid", "transliteration": "الواحد", "en": "The One, the All Inclusive, The Indivisible" },
  { "id": 67, "name": "As-Samad", "transliteration": "الصمد", "en": "The Satisfier of All Needs" },
  { "id": 68, "name": "Al-Qadir", "transliteration": "القادر", "en": "The All Powerful" },
  { "id": 69, "name": "Al-Muqtadir", "transliteration": "المقتدر", "en": "The Creator of All Power" },
  { "id": 70, "name": "Al-Muqaddim", "transliteration": "المقدم", "en": "The Expediter" },
  { "id": 71, "name": "Al-Mu'akhkhir", "transliteration": "المؤخر", "en": "The Delayer" },
  { "id": 72, "name": "Al-Awwal", "transliteration": "الأول", "en": "The First" },
  { "id": 73, "name": "Al-Akhir", "transliteration": "الآخر", "en": "The Last" },
  { "id": 74, "name": "Az-Zahir", "transliteration": "الظاهر", "en": "The Manifest One" },
  { "id": 75, "name": "Al-Batin", "transliteration": "الباطن", "en": "The Hidden One" },
  { "id": 76, "name": "Al-Wali", "transliteration": "الوالي", "en": "The Protecting Friend" },
  { "id": 77, "name": "Al-Muta'ali", "transliteration": "المتعالي", "en": "The Supreme One" },
  { "id": 78, "name": "Al-Barr", "transliteration": "البر", "en": "The Doer of Good" },
  { "id": 79, "name": "At-Tawwab", "transliteration": "التواب", "en": "The Guide to Repentance" },
  { "id": 80, "name": "Al-Muntaqim", "transliteration": "المنتقم", "en": "The Avenger" },
  { "id": 81, "name": "Al-Afuww", "transliteration": "العفو", "en": "The Forgiver" },
  { "id": 82, "name": "Ar-Ra'uf", "transliteration": "الرؤوف", "en": "The Clement" },
  { "id": 83, "name": "Malik-al-Mulk", "transliteration": "مالك الملك", "en": "The Owner of All" },
  { "id": 84, "name": "Dhul-Jalal wal-Ikram", "transliteration": "ذو الجلال والإكرام", "en": "The Lord of Majesty and Bounty" },
  { "id": 85, "name": "Al-Muqsit", "transliteration": "المقسط", "en": "The Equitable One" },
  { "id": 86, "name": "Al-Jami'", "transliteration": "الجامع", "en": "The Gatherer" },
  { "id": 87, "name": "Al-Ghani", "transliteration": "الغني", "en": "The Rich One" },
  { "id": 88, "name": "Al-Mughni", "transliteration": "المغني", "en": "The Enricher" },
  { "id": 89, "name": "Al-Mani'", "transliteration": "المانع", "en": "The Preventer of Harm" },
  { "id": 90, "name": "Ad-Darr", "transliteration": "الضار", "en": "The Creator of The Harmful" },
  { "id": 91, "name": "An-Nafi'", "transliteration": "النافع", "en": "The Creator of Good" },
  { "id": 92, "name": "An-Nur", "transliteration": "النور", "en": "The Light" },
  { "id": 93, "name": "Al-Hadi", "transliteration": "الهادي", "en": "The Guide" },
  { "id": 94, "name": "Al-Badi", "transliteration": "البديع", "en": "The Originator" },
  { "id": 95, "name": "Al-Baqi", "transliteration": "الباقي", "en": "The Everlasting One" },
  { "id": 96, "name": "Al-Warith", "transliteration": "الوارث", "en": "The Inheritor of All" },
  { "id": 97, "name": "Ar-Rashid", "transliteration": "الرشيد", "en": "The Righteous Teacher" },
  { "id": 98, "name": "As-Sabur", "transliteration": "الصبور", "en": "The Patient One" }
];
