export const PRAYER_NAMES = ['Fajr', 'Sunrise', 'Dhuhr', 'Asr', 'Maghrib', 'Isha'];

export const ALLAH_NAMES = [
  { "id": 1, "name": "Ar-Rahmān", "transliteration": "الرَّحْمَنُ", "en": "The Most or Entirely Merciful" },
  { "id": 2, "name": "Ar-Rahīm", "transliteration": "الرَّحِيمُ", "en": "The Bestower of Mercy" },
  { "id": 3, "name": "Al-Malik", "transliteration": "الْمَلِكُ", "en": "The King and Owner of Dominion" },
  { "id": 4, "name": "Al-Quddūs", "transliteration": "الْقُدُّوسُ", "en": "The Absolutely Pure" },
  { "id": 5, "name": "As-Salām", "transliteration": "السَّلَامُ", "en": "The Source of Peace" },
  { "id": 6, "name": "Al-Mu'min", "transliteration": "الْمُؤْمِنُ", "en": "The Giver of Security" },
  { "id": 7, "name": "Al-Muhaymin", "transliteration": "الْمُهَيْمِنُ", "en": "The Watchful, The Overseer" },
  { "id": 8, "name": "Al-'Azīz", "transliteration": "الْعَزِيزُ", "en": "The Almighty, The Exalted" },
  { "id": 9, "name": "Al-Jabbār", "transliteration": "الْجَبَّارُ", "en": "The Restorer, The Compeller" },
  { "id": 10, "name": "Al-Mutakabbir", "transliteration": "الْمُتَكَبِّرُ", "en": "The Supreme, The Majestic" },
  { "id": 11, "name": "Al-Khāliq", "transliteration": "الْخَالِقُ", "en": "The Creator, The Maker" },
  { "id": 12, "name": "Al-Bāri'", "transliteration": "الْبَارِئُ", "en": "The Originator" },
  { "id": 13, "name": "Al-Muṣawwir", "transliteration": "الْمُصَوِّرُ", "en": "The Fashioner" },
  { "id": 14, "name": "Al-Ghaffār", "transliteration": "الْغَفَّارُ", "en": "The Constant Forgiver" },
  { "id": 15, "name": "Al-Qahhār", "transliteration": "الْقَهَّارُ", "en": "The Subduer, The Ever-Dominating" },
  { "id": 16, "name": "Al-Wahhāb", "transliteration": "الْوَهَّابُ", "en": "The Giver of Gifts" },
  { "id": 17, "name": "Ar-Razzāq", "transliteration": "الرَّزَّاقُ", "en": "The Ever-Providing" },
  { "id": 18, "name": "Al-Fattāḥ", "transliteration": "الْفَتَّاحُ", "en": "The Opener, The Judge" },
  { "id": 19, "name": "Al-'Alīm", "transliteration": "الْعَلِيمُ", "en": "The All-Knowing" },
  { "id": 20, "name": "Al-Qābiḍ", "transliteration": "الْقَابِضُ", "en": "The Withholder" },
  { "id": 21, "name": "Al-Bāsiṭ", "transliteration": "الْبَاسِطُ", "en": "The Extender" },
  { "id": 22, "name": "Al-Khāfiḍ", "transliteration": "الْخَافِضُ", "en": "The Reducer" },
  { "id": 23, "name": "Ar-Rāfi'", "transliteration": "الرَّافِعُ", "en": "The Exalter" },
  { "id": 24, "name": "Al-Mu'izz", "transliteration": "الْمُعِزُّ", "en": "The Bestower of Honour" },
  { "id": 25, "name": "Al-Mudhill", "transliteration": "الْمُذِلُّ", "en": "The Humiliator" },
  { "id": 26, "name": "As-Samī'", "transliteration": "السَّمِيعُ", "en": "The All-Hearing" },
  { "id": 27, "name": "Al-Baṣīr", "transliteration": "الْبَصِيرُ", "en": "The All-Seeing" },
  { "id": 28, "name": "Al-Ḥakam", "transliteration": "الْحَكَمُ", "en": "The Judge" },
  { "id": 29, "name": "Al-'Adl", "transliteration": "الْعَدْلُ", "en": "The Utterly Just" },
  { "id": 30, "name": "Al-Laṭīf", "transliteration": "اللَّطِيفُ", "en": "The Subtle One, The Most Gentle" },
  { "id": 31, "name": "Al-Khabīr", "transliteration": "الْخَبِيرُ", "en": "The All-Aware" },
  { "id": 32, "name": "Al-Ḥalīm", "transliteration": "الْحَلِيمُ", "en": "The Most Forbearing" },
  { "id": 33, "name": "Al-'Aẓīm", "transliteration": "الْعَظِيمُ", "en": "The Magnificent" },
  { "id": 34, "name": "Al-Ghafūr", "transliteration": "الْغَفُورُ", "en": "The All-Forgiving" },
  { "id": 35, "name": "Ash-Shakūr", "transliteration": "الشَّكُورُ", "en": "The Most Appreciative" },
  { "id": 36, "name": "Al-'Alī", "transliteration": "الْعَلِيُّ", "en": "The Most High" },
  { "id": 37, "name": "Al-Kabīr", "transliteration": "الْكَبِيرُ", "en": "The Greatest" },
  { "id": 38, "name": "Al-Ḥafīẓ", "transliteration": "الْحَفِيظُ", "en": "The Preserver" },
  { "id": 39, "name": "Al-Muqīt", "transliteration": "الْمُقِيتُ", "en": "The Sustainer" },
  { "id": 40, "name": "Al-Ḥasīb", "transliteration": "الْحَسِيبُ", "en": "The Reckoner" },
  { "id": 41, "name": "Al-Jalīl", "transliteration": "الْجَلِيلُ", "en": "The Majestic" },
  { "id": 42, "name": "Al-Karīm", "transliteration": "الْكَرِيمُ", "en": "The Most Generous" },
  { "id": 43, "name": "Ar-Raqīb", "transliteration": "الرَّقِيبُ", "en": "The Watchful" },
  { "id": 44, "name": "Al-Mujīb", "transliteration": "الْمُجِيبُ", "en": "The Responder to Prayer" },
  { "id": 45, "name": "Al-Wāsi'", "transliteration": "الْوَاسِعُ", "en": "The All-Encompassing" },
  { "id": 46, "name": "Al-Ḥakīm", "transliteration": "الْحَكِيمُ", "en": "The All-Wise" },
  { "id": 47, "name": "Al-Wadūd", "transliteration": "الْوَدُودُ", "en": "The Most Loving" },
  { "id": 48, "name": "Al-Majīd", "transliteration": "الْمَجِيدُ", "en": "The Glorious" },
  { "id": 49, "name": "Al-Bā'ith", "transliteration": "الْبَاعِثُ", "en": "The Resurrector" },
  { "id": 50, "name": "Ash-Shahīd", "transliteration": "الشَّهِيدُ", "en": "The Witness" },
  { "id": 51, "name": "Al-Ḥaqq", "transliteration": "الْحَقُّ", "en": "The Truth" },
  { "id": 52, "name": "Al-Wakīl", "transliteration": "الْوَكِيلُ", "en": "The Trustee, The Disposer of Affairs" },
  { "id": 53, "name": "Al-Qawī", "transliteration": "الْقَوِيُّ", "en": "The All-Strong" },
  { "id": 54, "name": "Al-Matīn", "transliteration": "الْمَتِينُ", "en": "The Firm, The Steadfast" },
  { "id": 55, "name": "Al-Walī", "transliteration": "الْوَلِيُّ", "en": "The Protecting Associate" },
  { "id": 56, "name": "Al-Ḥamīd", "transliteration": "الْحَمِيدُ", "en": "The Praiseworthy" },
  { "id": 57, "name": "Al-Muḥṣī", "transliteration": "الْمُحْصِي", "en": "The All-Enumerating" },
  { "id": 58, "name": "Al-Mubdi'", "transliteration": "الْمُبْدِئُ", "en": "The Originator" },
  { "id": 59, "name": "Al-Mu'īd", "transliteration": "الْمُعِيدُ", "en": "The Restorer" },
  { "id": 60, "name": "Al-Muḥyī", "transliteration": "الْمُحْيِي", "en": "The Giver of Life" },
  { "id": 61, "name": "Al-Mumīt", "transliteration": "الْمُمِيتُ", "en": "The Taker of Life" },
  { "id": 62, "name": "Al-Ḥayy", "transliteration": "الْحَيُّ", "en": "The Ever-Living" },
  { "id": 63, "name": "Al-Qayyūm", "transliteration": "الْقَيُّومُ", "en": "The Self-Subsisting" },
  { "id": 64, "name": "Al-Wājid", "transliteration": "الْوَاجِدُ", "en": "The Perceiver" },
  { "id": 65, "name": "Al-Mājid", "transliteration": "الْمَاجِدُ", "en": "The Illustrious, the Magnificent" },
  { "id": 66, "name": "Al-Wāḥid", "transliteration": "الْوَاحِدُ", "en": "The One" },
  { "id": 67, "name": "Al-Aḥad", "transliteration": "الْأَحَدُ", "en": "The Unique" },
  { "id": 68, "name": "Aṣ-Ṣamad", "transliteration": "الصَّمَدُ", "en": "The Eternal, The Independent" },
  { "id": 69, "name": "Al-Qādir", "transliteration": "الْقَادِرُ", "en": "The All-Powerful" },
  { "id": 70, "name": "Al-Muqtadir", "transliteration": "الْمُقْتَدِرُ", "en": "The All-Determiner" },
  { "id": 71, "name": "Al-Muqaddim", "transliteration": "الْمُقَدِّمُ", "en": "The Promoter, The Expediter" },
  { "id": 72, "name": "Al-Mu'akhkhir", "transliteration": "الْمُؤَخِّرُ", "en": "The Delayer" },
  { "id": 73, "name": "Al-'Awwal", "transliteration": "الْأَوَّلُ", "en": "The First" },
  { "id": 74, "name": "Al-'Ākhir", "transliteration": "الْآخِرُ", "en": "The Last" },
  { "id": 75, "name": "Aẓ-Ẓāhir", "transliteration": "الظَّاهِرُ", "en": "The Manifest" },
  { "id": 76, "name": "Al-Bāṭin", "transliteration": "الْبَاطِنُ", "en": "The Hidden" },
  { "id": 77, "name": "Al-Wālī", "transliteration": "الْوَالِي", "en": "The Governor, The Patron" },
  { "id": 78, "name": "Al-Muta'ālī", "transliteration": "الْمُتَعَالِي", "en": "The Self-Exalted" },
  { "id": 79, "name": "Al-Barr", "transliteration": "الْبَرُّ", "en": "The Source of All Goodness" },
  { "id": 80, "name": "At-Tawwāb", "transliteration": "التَّوَّابُ", "en": "The Ever-Acceptor of Repentance" },
  { "id": 81, "name": "Al-Muntaqim", "transliteration": "الْمُنْتَقِمُ", "en": "The Avenger" },
  { "id": 82, "name": "Al-'Afūw", "transliteration": "الْعَفُوُّ", "en": "The Pardoner" },
  { "id": 83, "name": "Ar-Ra'ūf", "transliteration": "الرَّءُوفُ", "en": "The Most Kind" },
  { "id": 84, "name": "Mālik-ul-Mulk", "transliteration": "مَالِكُ الْمُلْكِ", "en": "Master of the Kingdom" },
  { "id": 85, "name": "Dhūl-Jalāli wal-'Ikrām", "transliteration": "ذُو الْجَلَالِ وَالْإِكْرَامِ", "en": "Lord of Majesty and Honour" },
  { "id": 86, "name": "Al-Muqsiṭ", "transliteration": "الْمُقْسِطُ", "en": "The Equitable" },
  { "id": 87, "name": "Al-Jāmi'", "transliteration": "الْجَامِعُ", "en": "The Gatherer, The Uniter" },
  { "id": 88, "name": "Al-Ghanī", "transliteration": "الْغَنِيُّ", "en": "The Self-Sufficient" },
  { "id": 89, "name": "Al-Mughnī", "transliteration": "الْمُغْنِي", "en": "The Enricher" },
  { "id": 90, "name": "Al-Māni'", "transliteration": "الْمَانِعُ", "en": "The Withholder" },
  { "id": 91, "name": "Aḍ-Ḍārr", "transliteration": "الضَّارُّ", "en": "The Distresser" },
  { "id": 92, "name": "An-Nāfi'", "transliteration": "النَّافِعُ", "en": "The Bestower of Benefits" },
  { "id": 93, "name": "An-Nūr", "transliteration": "النُّورُ", "en": "The Light" },
  { "id": 94, "name": "Al-Hādī", "transliteration": "الْهَادِي", "en": "The Guide" },
  { "id": 95, "name": "Al-Badī'", "transliteration": "الْبَدِيعُ", "en": "The Incomparable Originator" },
  { "id": 96, "name": "Al-Bāqī", "transliteration": "الْبَاقِي", "en": "The Everlasting" },
  { "id": 97, "name": "Al-Wārith", "transliteration": "الْوَارِثُ", "en": "The Ultimate Inheritor" },
  { "id": 98, "name": "Ar-Rashīd", "transliteration": "الرَّشِيدُ", "en": "The Guide to the Right Path" },
  { "id": 99, "name": "Aṣ-Ṣabūr", "transliteration": "الصَّبُورُ", "en": "The Most Patient" }
];

export const ALPHABET = [
    {
      "letter": "ا",
      "name": "Alif",
      "transliteration": "a, ā",
      "exampleWord": "ٱلْفَاتِحَة",
      "exampleTranslation": "Al-Fatiha",
      "exampleMeaning": "The Opening"
    },
    {
      "letter": "ب",
      "name": "Ba",
      "transliteration": "b",
      "exampleWord": "بِسْمِ",
      "exampleTranslation": "Bismillah",
      "exampleMeaning": "In the name of"
    },
    {
      "letter": "ت",
      "name": "Ta",
      "transliteration": "t",
      "exampleWord": "تَبَّتْ",
      "exampleTranslation": "Tabbat",
      "exampleMeaning": "Perish"
    },
    {
      "letter": "ث",
      "name": "Tha",
      "transliteration": "th",
      "exampleWord": "ثَمَرَةٍ",
      "exampleTranslation": "Thamaratin",
      "exampleMeaning": "A fruit"
    },
    {
      "letter": "ج",
      "name": "Jim",
      "transliteration": "j",
      "exampleWord": "جَاءَ",
      "exampleTranslation": "Jā'a",
      "exampleMeaning": "He came"
    },
    {
      "letter": "ح",
      "name": "Ha",
      "transliteration": "ḥ",
      "exampleWord": "الْحَمْدُ",
      "exampleTranslation": "Al-Hamdu",
      "exampleMeaning": "The praise"
    },
    {
      "letter": "خ",
      "name": "Kha",
      "transliteration": "kh",
      "exampleWord": "خَلَقَ",
      "exampleTranslation": "Khalaqa",
      "exampleMeaning": "He created"
    },
    {
      "letter": "د",
      "name": "Dal",
      "transliteration": "d",
      "exampleWord": "الدِّينِ",
      "exampleTranslation": "Ad-Dīn",
      "exampleMeaning": "The religion"
    },
    {
      "letter": "ذ",
      "name": "Dhal",
      "transliteration": "dh",
      "exampleWord": "ذَٰلِكَ",
      "exampleTranslation": "Dhālika",
      "exampleMeaning": "That"
    },
    {
      "letter": "ر",
      "name": "Ra",
      "transliteration": "r",
      "exampleWord": "رَبِّ",
      "exampleTranslation": "Rabb",
      "exampleMeaning": "Lord"
    },
    {
      "letter": "ز",
      "name": "Zain",
      "transliteration": "z",
      "exampleWord": "زُلْزِلَتِ",
      "exampleTranslation": "Zulzilat",
      "exampleMeaning": "Is shaken"
    },
    {
      "letter": "س",
      "name": "Sin",
      "transliteration": "s",
      "exampleWord": "سَبَّحَ",
      "exampleTranslation": "Sabbaḥa",
      "exampleMeaning": "He glorified"
    },
    {
      "letter": "ش",
      "name": "Shin",
      "transliteration": "sh",
      "exampleWord": "شَمْسِ",
      "exampleTranslation": "Shams",
      "exampleMeaning": "Sun"
    },
    {
      "letter": "ص",
      "name": "Sad",
      "transliteration": "ṣ",
      "exampleWord": "صِرَاطَ",
      "exampleTranslation": "Ṣirāṭa",
      "exampleMeaning": "Path"
    },
    {
      "letter": "ض",
      "name": "Dad",
      "transliteration": "ḍ",
      "exampleWord": "ضُحَىٰ",
      "exampleTranslation": "Ḍuḥā",
      "exampleMeaning": "Morning brightness"
    },
    {
      "letter": "ط",
      "name": "Ta",
      "transliteration": "ṭ",
      "exampleWord": "طَيْرًا",
      "exampleTranslation": "Ṭayran",
      "exampleMeaning": "Birds"
    },
    {
      "letter": "ظ",
      "name": "Dha",
      "transliteration": "ẓ",
      "exampleWord": "ظَهَرَ",
      "exampleTranslation": "Ẓahara",
      "exampleMeaning": "He appeared"
    },
    {
      "letter": "ع",
      "name": "Ain",
      "transliteration": "ʿ",
      "exampleWord": "عَلَىٰ",
      "exampleTranslation": "'Alā",
      "exampleMeaning": "Upon"
    },
    {
      "letter": "غ",
      "name": "Ghain",
      "transliteration": "gh",
      "exampleWord": "غَيْرِ",
      "exampleTranslation": "Ghayri",
      "exampleMeaning": "Other than"
    },
    {
      "letter": "ف",
      "name": "Fa",
      "transliteration": "f",
      "exampleWord": "فِي",
      "exampleTranslation": "Fī",
      "exampleMeaning": "In"
    },
    {
      "letter": "ق",
      "name": "Qaf",
      "transliteration": "q",
      "exampleWord": "قُلْ",
      "exampleTranslation": "Qul",
      "exampleMeaning": "Say"
    },
    {
      "letter": "ك",
      "name": "Kaf",
      "transliteration": "k",
      "exampleWord": "كِتَابُ",
      "exampleTranslation": "Kitābu",
      "exampleMeaning": "Book"
    },
    {
      "letter": "ل",
      "name": "Lam",
      "transliteration": "l",
      "exampleWord": "لِلَّهِ",
      "exampleTranslation": "Lillāhi",
      "exampleMeaning": "To Allah"
    },
    {
      "letter": "م",
      "name": "Mim",
      "transliteration": "m",
      "exampleWord": "مَالِكِ",
      "exampleTranslation": "Māliki",
      "exampleMeaning": "Master"
    },
    {
      "letter": "ن",
      "name": "Nun",
      "transliteration": "n",
      "exampleWord": "نَاسِ",
      "exampleTranslation": "Nās",
      "exampleMeaning": "Mankind"
    },
    {
      "letter": "ه",
      "name": "Ha",
      "transliteration": "h",
      "exampleWord": "هُوَ",
      "exampleTranslation": "Huwa",
      "exampleMeaning": "He"
    },
    {
      "letter": "و",
      "name": "Waw",
      "transliteration": "w, ū",
      "exampleWord": "وَ",
      "exampleTranslation": "Wa",
      "exampleMeaning": "And"
    },
    {
      "letter": "ي",
      "name": "Ya",
      "transliteration": "y, ī",
      "exampleWord": "يَوْمِ",
      "exampleTranslation": "Yawmi",
      "exampleMeaning": "Day"
    }
];
